export const INIT = 'INIT';

export const UPDATE_WINDOW = 'UPDATE_WINDOW';
export const UPDATE_POPUP = 'UPDATE_POPUP';
export const UPDATE_WALLET_POPUP = 'UPDATE_WALLET_POPUP';
export const UPDATE_ERROR_POPUP = 'UPDATE_ERROR_POPUP';

export const UPDATE_LTRJN_EDITOR = 'UPDATE_LTRJN_EDITOR';

export const UPDATE_ME = 'UPDATE_ME';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_EDITOR = 'UPDATE_PROFILE_EDITOR';

export const UPDATE_EVENTS = 'UPDATE_EVENTS';
export const UPDATE_SYNC = 'UPDATE_SYNC';
export const UPDATE_TXNS = 'UPDATE_TXNS';

export const RESET_STATE = 'RESET_STATE';
